baseURL = "https://tarduspura.github.io/"
title = "Tardus Pura 的个人空间"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  homeInfoParams = { Title = "Hi，Tardus Pura here", Content = "学习 | 户外 | 创作" }

[[menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 2

[[menu.main]]
  identifier = "posts"
  name = "笔记"
  url = "/posts/"
  weight = 3

[[menu.main]]
  identifier = "travel"
  name = "旅行&户外"
  url = "/travel/"
  weight = 4

[[menu.main]]
  identifier = "contemplate"
  name = "沉思"
  url = "/contemplate/"
  weight = 5

[[menu.main]]
  identifier = "projects"
  name = "项目"
  url = "/projects/"
  weight = 6

[[menu.main]]
  identifier = "her"
  name = "Her"
  url = "/about/"
  weight = 7  

  